# Generated by Django 4.1.7 on 2023-03-27 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0005_rename_task_task_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_links',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reward.tasklinks'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tasks',
            field=models.URLField(max_length=2000),
        ),
    ]
