# Generated by Django 4.1.7 on 2023-03-27 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0006_task_task_links_alter_task_tasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tasks',
            new_name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_links',
        ),
        migrations.DeleteModel(
            name='TaskLinks',
        ),
    ]
