# Generated by Django 4.1.7 on 2023-03-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0007_rename_tasks_task_task_remove_task_task_links_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
