# Generated by Django 4.1.7 on 2023-03-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0010_remove_task_task_tasklinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_complete',
            field=models.BooleanField(default=False),
        ),
    ]
