# Generated by Django 4.1.7 on 2023-03-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0012_alter_task_task_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_complete',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
