# Generated by Django 4.1.7 on 2023-03-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0013_alter_task_task_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklinks',
            name='task1',
            field=models.CharField(help_text='False', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tasklinks',
            name='task2',
            field=models.CharField(help_text='False', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tasklinks',
            name='task3',
            field=models.CharField(help_text='False', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tasklinks',
            name='task4',
            field=models.CharField(help_text='False', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tasklinks',
            name='ig',
            field=models.URLField(default='https://www.youtube.com/', max_length=2000),
        ),
        migrations.AlterField(
            model_name='tasklinks',
            name='share',
            field=models.URLField(default='https://www.youtube.com/', max_length=2000),
        ),
        migrations.AlterField(
            model_name='tasklinks',
            name='video',
            field=models.URLField(default='https://www.youtube.com/', max_length=2000),
        ),
        migrations.AlterField(
            model_name='tasklinks',
            name='youtubelink',
            field=models.URLField(default='https://www.youtube.com/', max_length=2000),
        ),
    ]
